### PR TITLE
Added allow cross domain GET requests

### PR DESCRIPTION
**Pull request by lvidarte**

### CODE REVIEW

**Comment by xaiki** [comment]
We're going to need a write up en the security implications to this.

**Comment by jmrunge** [comment]
We already have this in routes:

```
var accessControl = function(req, res, next) {
        res.header("Access-Control-Allow-Origin", "*");
        res.header("Access-Control-Allow-Headers", "X-Requested-With");
        next();
    };

    accessRoutes = [ 'images', '/uploadFile' ];
    _.each(accessRoutes, function(route) {
        app.all(route, accessControl);
    });
```

What would be the difference?

**Comment by lvidarte** [comment]
I didn't see that. I'll see this a bit more..

**Comment by josx** [comment]
It is only allowed to the accessRoutes, @lvidarte  maybe you can add there new paths.

**Comment by josx** [comment]
@lvidarte maybe this solve the problem:

``` javascript
var accessControl = function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
    res.header("Access-Control-Allow-Headers", "X-Requested-With");
    next();
};
```

If not check here https://developer.mozilla.org/en-US/docs/HTTP/Access_control_CORS

**Pull request closed without merging**
